CREATE TABLE IF NOT EXISTS export_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    merchant_id UUID NOT NULL,
    format VARCHAR(20) NOT NULL,
    platform VARCHAR(20) NOT NULL,
    data_types VARCHAR(255) NOT NULL,
    frequency VARCHAR(20),
    scheduled_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    chart_public_id UUID,
    account_public_id UUID,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by VARCHAR(255) DEFAULT 'system',
    last_modified_at TIMESTAMPTZ DEFAULT now(),
    last_modified_by VARCHAR(255) DEFAULT 'system'
);

CREATE TABLE IF NOT EXISTS export_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    merchant_id UUID NOT NULL,
    config_public_id UUID,
    format VARCHAR(20) NOT NULL,
    platform VARCHAR(20) NOT NULL,
    data_type VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    s3_key VARCHAR(512),
    file_size_bytes BIGINT,
    start_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL,
    error_message TEXT,
    expires_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by VARCHAR(255) DEFAULT 'system',
    last_modified_at TIMESTAMPTZ DEFAULT now(),
    last_modified_by VARCHAR(255) DEFAULT 'system'
);

CREATE INDEX IF NOT EXISTS idx_export_config_merchant_id ON export_config(merchant_id);
CREATE INDEX IF NOT EXISTS idx_export_config_scheduled ON export_config(scheduled_enabled) WHERE scheduled_enabled = TRUE;

CREATE INDEX IF NOT EXISTS idx_export_record_merchant_id ON export_record(merchant_id);
CREATE INDEX IF NOT EXISTS idx_export_record_config_public_id ON export_record(config_public_id);
CREATE INDEX IF NOT EXISTS idx_export_record_status ON export_record(status);
CREATE INDEX IF NOT EXISTS idx_export_record_expires_at ON export_record(expires_at);
