package com.krachtix.identity.core.entity

enum class OAuthClientSettingName {
    REQUIRE_AUTHORIZATION_CONSENT,
    REQUIRE_PROOF_KEY
}

enum class OAuthTokenSettingName {
    ACCESS_TOKEN_TIME_TO_LIVE,
    REFRESH_TOKEN_TIME_TO_LIVE,
    REUSE_REFRESH_TOKENS,
    ID_TOKEN_SIGNATURE_ALGORITHM,
    ACCESS_TOKEN_FORMAT,
    AUTHORIZATION_CODE_TIME_TO_LIVE,
    DEVICE_CODE_TIME_TO_LIVE
}

enum class OAuthUserSettingName {
    TIMEZONE,
    DATE_FORMAT,
    NUMBER_FORMAT,
    GUIDED_TOUR_VIEW_COUNT,
    INVITATION_STATUS,
    LOCALE,
    ENVIRONMENT_PREFERENCE,
    ENVIRONMENT_LAST_SWITCHED_AT,
    REGISTRATION_COMPLETE
}
