DATABASE_NAME: krachtix_sandbox
SERVER_PORT: 80

DB_HOST: postgres

IDENTITY_BASEURL: https://id.id.krachtix.com

ALLOWED_CORS_ORIGINS: "https://sandbox.krachtix.com,https://id.id.krachtix.com"

HAZELCAST_CLUSTER_NAME: sandbox

CORE_MS_BASE_URL: http://core:80
NOTIFICATION_MS_BASE_URL: http://notification:80
AUDIT_MS_BASE_URL: http://audit:80
RAG_MS_BASE_URL: http://rag:80
