DATABASE_NAME: krachtix
SERVER_PORT: 80

IDENTITY_BASEURL: https://id.krachtix.com

ALLOWED_CORS_ORIGINS: "https://app.krachtix.com,https://checkout.krachtix.com,https://id.krachtix.com"
FRONTEND_URL: https://app.krachtix.com

HAZELCAST_MEMBERS: krachtix-hazelcast:5701

NOTIFICATION_MS_BASE_URL: http://notification:80
AUDIT_MS_BASE_URL: http://audit:80
CORE_MS_BASE_URL: http://platforms:80

S3_ENDPOINT: https://s3.eu-west-1.amazonaws.com
S3_REGION: eu-west-1
S3_BUCKET: krachtix

SPRINGDOC_ENABLED: false
