DATABASE_NAME: krachtix

server:
  port: 80

IDENTITY_BASEURL: https://id.id.krachtix.com

ALLOWED_CORS_ORIGINS: "http://localhost:3002,http://localhost:3000"

HAZELCAST_CLUSTER_NAME: dev

CORE_MS_BASE_URL: http://core:80
NOTIFICATION_MS_BASE_URL: http://notification:80
AUDIT_MS_BASE_URL: http://audit:80
RAG_MS_BASE_URL: http://rag:80
