package com.krachtix.commons.performance;

public enum MetricTag {

    INTEGRATOR, ERROR_CODE, STATUS_CODE, STATUS, DESTINATION_BANK, SERVER_ERROR, MONITORING_TYPE, SERVICE_PROVIDER, PRODUCT,
    EXECUTION_NAME, EXECUTION_TIME, EXECUTION_TIME_UNIT
}
