INSERT INTO currency (name, code, symbol, symbol_native, iso_num, iso_digits, decimals, type, enabled)
VALUES
    ('UAE Dirham', 'AED', 'د.إ', 'د.إ', 784, 2, 2, 'FIAT', true),
    ('Afghani', 'AFN', '؋', '؋', 971, 2, 2, 'FIAT', true),
    ('Lek', 'ALL', 'L', 'L', 8, 2, 2, 'FIAT', true),
    ('Armenian Dram', 'AMD', '֏', '֏', 51, 2, 2, 'FIAT', true),
    ('Kwanza', 'AOA', 'Kz', 'Kz', 973, 2, 2, 'FIAT', true),
    ('Argentine Peso', 'ARS', '$', '$', 32, 2, 2, 'FIAT', true),
    ('Australian Dollar', 'AUD', 'A$', '$', 36, 2, 2, 'FIAT', true),
    ('Aruban Florin', 'AWG', 'ƒ', 'ƒ', 533, 2, 2, 'FIAT', true),
    ('Azerbaijan Manat', 'AZN', '₼', '₼', 944, 2, 2, 'FIAT', true),
    ('Convertible Mark', 'BAM', 'KM', 'KM', 977, 2, 2, 'FIAT', true),
    ('Barbados Dollar', 'BBD', '$', '$', 52, 2, 2, 'FIAT', true),
    ('Taka', 'BDT', '৳', '৳', 50, 2, 2, 'FIAT', true),
    ('Bulgarian Lev', 'BGN', 'лв', 'лв', 975, 2, 2, 'FIAT', true),
    ('Bahraini Dinar', 'BHD', '.د.ب', '.د.ب', 48, 3, 3, 'FIAT', true),
    ('Burundi Franc', 'BIF', 'FBu', 'FBu', 108, 0, 0, 'FIAT', true),
    ('Bermudian Dollar', 'BMD', '$', '$', 60, 2, 2, 'FIAT', true),
    ('Brunei Dollar', 'BND', '$', '$', 96, 2, 2, 'FIAT', true),
    ('Boliviano', 'BOB', 'Bs.', 'Bs.', 68, 2, 2, 'FIAT', true),
    ('Brazilian Real', 'BRL', 'R$', 'R$', 986, 2, 2, 'FIAT', true),
    ('Bahamian Dollar', 'BSD', '$', '$', 44, 2, 2, 'FIAT', true),
    ('Ngultrum', 'BTN', 'Nu.', 'Nu.', 64, 2, 2, 'FIAT', true),
    ('Pula', 'BWP', 'P', 'P', 72, 2, 2, 'FIAT', true),
    ('Belarusian Ruble', 'BYN', 'Br', 'Br', 933, 2, 2, 'FIAT', true),
    ('Belize Dollar', 'BZD', 'BZ$', '$', 84, 2, 2, 'FIAT', true),
    ('Canadian Dollar', 'CAD', 'C$', '$', 124, 2, 2, 'FIAT', true),
    ('Congolese Franc', 'CDF', 'FC', 'FC', 976, 2, 2, 'FIAT', true),
    ('Swiss Franc', 'CHF', 'Fr', 'CHF', 756, 2, 2, 'FIAT', true),
    ('Chilean Peso', 'CLP', '$', '$', 152, 0, 0, 'FIAT', true),
    ('Yuan Renminbi', 'CNY', '¥', '¥', 156, 2, 2, 'FIAT', true),
    ('Colombian Peso', 'COP', '$', '$', 170, 2, 2, 'FIAT', true),
    ('Costa Rican Colon', 'CRC', '₡', '₡', 188, 2, 2, 'FIAT', true),
    ('Cuban Peso', 'CUP', '$', '$', 192, 2, 2, 'FIAT', true),
    ('Cabo Verde Escudo', 'CVE', '$', '$', 132, 2, 2, 'FIAT', true),
    ('Czech Koruna', 'CZK', 'Kč', 'Kč', 203, 2, 2, 'FIAT', true),
    ('Djibouti Franc', 'DJF', 'Fdj', 'Fdj', 262, 0, 0, 'FIAT', true),
    ('Danish Krone', 'DKK', 'kr', 'kr', 208, 2, 2, 'FIAT', true),
    ('Dominican Peso', 'DOP', 'RD$', '$', 214, 2, 2, 'FIAT', true),
    ('Algerian Dinar', 'DZD', 'د.ج', 'د.ج', 12, 2, 2, 'FIAT', true),
    ('Egyptian Pound', 'EGP', '£', 'ج.م', 818, 2, 2, 'FIAT', true),
    ('Nakfa', 'ERN', 'Nfk', 'Nfk', 232, 2, 2, 'FIAT', true),
    ('Ethiopian Birr', 'ETB', 'Br', 'Br', 230, 2, 2, 'FIAT', true),
    ('Euro', 'EUR', '€', '€', 978, 2, 2, 'FIAT', true),
    ('Fiji Dollar', 'FJD', '$', '$', 242, 2, 2, 'FIAT', true),
    ('Falkland Islands Pound', 'FKP', '£', '£', 238, 2, 2, 'FIAT', true),
    ('Pound Sterling', 'GBP', '£', '£', 826, 2, 2, 'FIAT', true),
    ('Lari', 'GEL', '₾', '₾', 981, 2, 2, 'FIAT', true),
    ('Ghana Cedi', 'GHS', '₵', '₵', 936, 2, 2, 'FIAT', true),
    ('Gibraltar Pound', 'GIP', '£', '£', 292, 2, 2, 'FIAT', true),
    ('Dalasi', 'GMD', 'D', 'D', 270, 2, 2, 'FIAT', true),
    ('Guinean Franc', 'GNF', 'FG', 'FG', 324, 0, 0, 'FIAT', true),
    ('Quetzal', 'GTQ', 'Q', 'Q', 320, 2, 2, 'FIAT', true),
    ('Guyana Dollar', 'GYD', '$', '$', 328, 2, 2, 'FIAT', true),
    ('Hong Kong Dollar', 'HKD', 'HK$', '$', 344, 2, 2, 'FIAT', true),
    ('Lempira', 'HNL', 'L', 'L', 340, 2, 2, 'FIAT', true),
    ('Gourde', 'HTG', 'G', 'G', 332, 2, 2, 'FIAT', true),
    ('Forint', 'HUF', 'Ft', 'Ft', 348, 2, 2, 'FIAT', true),
    ('Rupiah', 'IDR', 'Rp', 'Rp', 360, 2, 2, 'FIAT', true),
    ('New Israeli Sheqel', 'ILS', '₪', '₪', 376, 2, 2, 'FIAT', true),
    ('Indian Rupee', 'INR', '₹', '₹', 356, 2, 2, 'FIAT', true),
    ('Iraqi Dinar', 'IQD', 'ع.د', 'ع.د', 368, 3, 3, 'FIAT', true),
    ('Iranian Rial', 'IRR', '﷼', '﷼', 364, 2, 2, 'FIAT', true),
    ('Iceland Krona', 'ISK', 'kr', 'kr', 352, 0, 0, 'FIAT', true),
    ('Jamaican Dollar', 'JMD', 'J$', '$', 388, 2, 2, 'FIAT', true),
    ('Jordanian Dinar', 'JOD', 'د.ا', 'د.ا', 400, 3, 3, 'FIAT', true),
    ('Yen', 'JPY', '¥', '¥', 392, 0, 0, 'FIAT', true),
    ('Kenyan Shilling', 'KES', 'KSh', 'KSh', 404, 2, 2, 'FIAT', true),
    ('Som', 'KGS', 'с', 'с', 417, 2, 2, 'FIAT', true),
    ('Riel', 'KHR', '៛', '៛', 116, 2, 2, 'FIAT', true),
    ('Comorian Franc', 'KMF', 'CF', 'CF', 174, 0, 0, 'FIAT', true),
    ('North Korean Won', 'KPW', '₩', '₩', 408, 2, 2, 'FIAT', false),
    ('Won', 'KRW', '₩', '₩', 410, 0, 0, 'FIAT', true),
    ('Kuwaiti Dinar', 'KWD', 'د.ك', 'د.ك', 414, 3, 3, 'FIAT', true),
    ('Cayman Islands Dollar', 'KYD', '$', '$', 136, 2, 2, 'FIAT', true),
    ('Tenge', 'KZT', '₸', '₸', 398, 2, 2, 'FIAT', true),
    ('Lao Kip', 'LAK', '₭', '₭', 418, 2, 2, 'FIAT', true),
    ('Lebanese Pound', 'LBP', 'ل.ل', 'ل.ل', 422, 2, 2, 'FIAT', true),
    ('Sri Lanka Rupee', 'LKR', 'Rs', 'රු', 144, 2, 2, 'FIAT', true),
    ('Liberian Dollar', 'LRD', '$', '$', 430, 2, 2, 'FIAT', true),
    ('Loti', 'LSL', 'L', 'L', 426, 2, 2, 'FIAT', true),
    ('Libyan Dinar', 'LYD', 'ل.د', 'ل.د', 434, 3, 3, 'FIAT', true),
    ('Moroccan Dirham', 'MAD', 'د.م.', 'د.م.', 504, 2, 2, 'FIAT', true),
    ('Moldovan Leu', 'MDL', 'L', 'L', 498, 2, 2, 'FIAT', true),
    ('Malagasy Ariary', 'MGA', 'Ar', 'Ar', 969, 2, 2, 'FIAT', true),
    ('Denar', 'MKD', 'ден', 'ден', 807, 2, 2, 'FIAT', true),
    ('Kyat', 'MMK', 'K', 'K', 104, 2, 2, 'FIAT', true),
    ('Tugrik', 'MNT', '₮', '₮', 496, 2, 2, 'FIAT', true),
    ('Pataca', 'MOP', 'MOP$', 'MOP$', 446, 2, 2, 'FIAT', true),
    ('Ouguiya', 'MRU', 'UM', 'UM', 929, 2, 2, 'FIAT', true),
    ('Mauritius Rupee', 'MUR', '₨', '₨', 480, 2, 2, 'FIAT', true),
    ('Rufiyaa', 'MVR', 'Rf', 'Rf', 462, 2, 2, 'FIAT', true),
    ('Malawi Kwacha', 'MWK', 'MK', 'MK', 454, 2, 2, 'FIAT', true),
    ('Mexican Peso', 'MXN', '$', '$', 484, 2, 2, 'FIAT', true),
    ('Malaysian Ringgit', 'MYR', 'RM', 'RM', 458, 2, 2, 'FIAT', true),
    ('Mozambique Metical', 'MZN', 'MT', 'MT', 943, 2, 2, 'FIAT', true),
    ('Namibia Dollar', 'NAD', '$', '$', 516, 2, 2, 'FIAT', true),
    ('Naira', 'NGN', '₦', '₦', 566, 2, 2, 'FIAT', true),
    ('Cordoba Oro', 'NIO', 'C$', 'C$', 558, 2, 2, 'FIAT', true),
    ('Norwegian Krone', 'NOK', 'kr', 'kr', 578, 2, 2, 'FIAT', true),
    ('Nepalese Rupee', 'NPR', '₨', '₨', 524, 2, 2, 'FIAT', true),
    ('New Zealand Dollar', 'NZD', 'NZ$', '$', 554, 2, 2, 'FIAT', true),
    ('Rial Omani', 'OMR', 'ر.ع.', 'ر.ع.', 512, 3, 3, 'FIAT', true),
    ('Balboa', 'PAB', 'B/.', 'B/.', 590, 2, 2, 'FIAT', true),
    ('Sol', 'PEN', 'S/', 'S/', 604, 2, 2, 'FIAT', true),
    ('Kina', 'PGK', 'K', 'K', 598, 2, 2, 'FIAT', true),
    ('Philippine Peso', 'PHP', '₱', '₱', 608, 2, 2, 'FIAT', true),
    ('Pakistan Rupee', 'PKR', '₨', '₨', 586, 2, 2, 'FIAT', true),
    ('Zloty', 'PLN', 'zł', 'zł', 985, 2, 2, 'FIAT', true),
    ('Guarani', 'PYG', '₲', '₲', 600, 0, 0, 'FIAT', true),
    ('Qatari Rial', 'QAR', 'ر.ق', 'ر.ق', 634, 2, 2, 'FIAT', true),
    ('Romanian Leu', 'RON', 'lei', 'lei', 946, 2, 2, 'FIAT', true),
    ('Serbian Dinar', 'RSD', 'дин.', 'дин.', 941, 2, 2, 'FIAT', true),
    ('Russian Ruble', 'RUB', '₽', '₽', 643, 2, 2, 'FIAT', false),
    ('Rwanda Franc', 'RWF', 'FRw', 'FRw', 646, 0, 0, 'FIAT', true),
    ('Saudi Riyal', 'SAR', '﷼', '﷼', 682, 2, 2, 'FIAT', true),
    ('Solomon Islands Dollar', 'SBD', '$', '$', 90, 2, 2, 'FIAT', true),
    ('Seychelles Rupee', 'SCR', '₨', '₨', 690, 2, 2, 'FIAT', true),
    ('Sudanese Pound', 'SDG', 'ج.س.', 'ج.س.', 938, 2, 2, 'FIAT', true),
    ('Swedish Krona', 'SEK', 'kr', 'kr', 752, 2, 2, 'FIAT', true),
    ('Singapore Dollar', 'SGD', 'S$', '$', 702, 2, 2, 'FIAT', true),
    ('Saint Helena Pound', 'SHP', '£', '£', 654, 2, 2, 'FIAT', true),
    ('Leone', 'SLE', 'Le', 'Le', 925, 2, 2, 'FIAT', true),
    ('Somali Shilling', 'SOS', 'S', 'S', 706, 2, 2, 'FIAT', true),
    ('Surinam Dollar', 'SRD', '$', '$', 968, 2, 2, 'FIAT', true),
    ('South Sudanese Pound', 'SSP', '£', '£', 728, 2, 2, 'FIAT', true),
    ('Dobra', 'STN', 'Db', 'Db', 930, 2, 2, 'FIAT', true),
    ('El Salvador Colon', 'SVC', '$', '$', 222, 2, 2, 'FIAT', true),
    ('Syrian Pound', 'SYP', '£', 'ل.س', 760, 2, 2, 'FIAT', true),
    ('Lilangeni', 'SZL', 'L', 'L', 748, 2, 2, 'FIAT', true),
    ('Baht', 'THB', '฿', '฿', 764, 2, 2, 'FIAT', true),
    ('Somoni', 'TJS', 'SM', 'SM', 972, 2, 2, 'FIAT', true),
    ('Turkmenistan New Manat', 'TMT', 'm', 'm', 934, 2, 2, 'FIAT', true),
    ('Tunisian Dinar', 'TND', 'د.ت', 'د.ت', 788, 3, 3, 'FIAT', true),
    ('Pa''anga', 'TOP', 'T$', 'T$', 776, 2, 2, 'FIAT', true),
    ('Turkish Lira', 'TRY', '₺', '₺', 949, 2, 2, 'FIAT', true),
    ('Trinidad and Tobago Dollar', 'TTD', 'TT$', '$', 780, 2, 2, 'FIAT', true),
    ('New Taiwan Dollar', 'TWD', 'NT$', '$', 901, 2, 2, 'FIAT', true),
    ('Tanzanian Shilling', 'TZS', 'TSh', 'TSh', 834, 2, 2, 'FIAT', true),
    ('Hryvnia', 'UAH', '₴', '₴', 980, 2, 2, 'FIAT', true),
    ('Uganda Shilling', 'UGX', 'USh', 'USh', 800, 0, 0, 'FIAT', true),
    ('US Dollar', 'USD', '$', '$', 840, 2, 2, 'FIAT', true),
    ('Peso Uruguayo', 'UYU', '$U', '$', 858, 2, 2, 'FIAT', true),
    ('Uzbekistan Sum', 'UZS', 'so''m', 'so''m', 860, 2, 2, 'FIAT', true),
    ('Bolívar Soberano', 'VES', 'Bs.S', 'Bs.S', 928, 2, 2, 'FIAT', true),
    ('Dong', 'VND', '₫', '₫', 704, 0, 0, 'FIAT', true),
    ('Vatu', 'VUV', 'VT', 'VT', 548, 0, 0, 'FIAT', true),
    ('Tala', 'WST', 'WS$', 'WS$', 882, 2, 2, 'FIAT', true),
    ('CFA Franc BEAC', 'XAF', 'FCFA', 'FCFA', 950, 0, 0, 'FIAT', true),
    ('East Caribbean Dollar', 'XCD', '$', '$', 951, 2, 2, 'FIAT', true),
    ('CFA Franc BCEAO', 'XOF', 'CFA', 'CFA', 952, 0, 0, 'FIAT', true),
    ('CFP Franc', 'XPF', '₣', '₣', 953, 0, 0, 'FIAT', true),
    ('Yemeni Rial', 'YER', '﷼', '﷼', 886, 2, 2, 'FIAT', true),
    ('Rand', 'ZAR', 'R', 'R', 710, 2, 2, 'FIAT', true),
    ('Zambian Kwacha', 'ZMW', 'ZK', 'ZK', 967, 2, 2, 'FIAT', true),
    ('Zimbabwe Gold', 'ZWG', 'ZiG', 'ZiG', 924, 2, 2, 'FIAT', true),
    ('Bitcoin', 'BTC', '₿', '₿', NULL, 8, 8, 'CRYPTO', true),
    ('Ethereum', 'ETH', 'Ξ', 'Ξ', NULL, 18, 18, 'CRYPTO', true),
    ('Tether', 'USDT', '₮', '₮', NULL, 6, 6, 'CRYPTO', true),
    ('USD Coin', 'USDC', '$', '$', NULL, 6, 6, 'CRYPTO', true),
    ('Binance Coin', 'BNB', 'BNB', 'BNB', NULL, 8, 8, 'CRYPTO', true),
    ('XRP', 'XRP', 'XRP', 'XRP', NULL, 6, 6, 'CRYPTO', true),
    ('Cardano', 'ADA', '₳', '₳', NULL, 6, 6, 'CRYPTO', true),
    ('Solana', 'SOL', 'SOL', 'SOL', NULL, 9, 9, 'CRYPTO', true),
    ('Dogecoin', 'DOGE', 'Ð', 'Ð', NULL, 8, 8, 'CRYPTO', true),
    ('Polkadot', 'DOT', 'DOT', 'DOT', NULL, 10, 10, 'CRYPTO', true),
    ('Polygon', 'MATIC', 'MATIC', 'MATIC', NULL, 18, 18, 'CRYPTO', true),
    ('Litecoin', 'LTC', 'Ł', 'Ł', NULL, 8, 8, 'CRYPTO', true),
    ('Avalanche', 'AVAX', 'AVAX', 'AVAX', NULL, 18, 18, 'CRYPTO', true),
    ('Chainlink', 'LINK', 'LINK', 'LINK', NULL, 18, 18, 'CRYPTO', true),
    ('Uniswap', 'UNI', 'UNI', 'UNI', NULL, 18, 18, 'CRYPTO', true),
    ('Stellar', 'XLM', 'XLM', 'XLM', NULL, 7, 7, 'CRYPTO', true),
    ('Monero', 'XMR', 'ɱ', 'ɱ', NULL, 12, 12, 'CRYPTO', true),
    ('Cosmos', 'ATOM', 'ATOM', 'ATOM', NULL, 6, 6, 'CRYPTO', true),
    ('Dai', 'DAI', 'DAI', 'DAI', NULL, 18, 18, 'CRYPTO', true),
    ('Tron', 'TRX', 'TRX', 'TRX', NULL, 6, 6, 'CRYPTO', true),
    ('Wrapped Bitcoin', 'WBTC', 'WBTC', 'WBTC', NULL, 8, 8, 'CRYPTO', true),
    ('Shiba Inu', 'SHIB', 'SHIB', 'SHIB', NULL, 18, 18, 'CRYPTO', true),
    ('Aave', 'AAVE', 'AAVE', 'AAVE', NULL, 18, 18, 'CRYPTO', true),
    ('Algorand', 'ALGO', 'ALGO', 'ALGO', NULL, 6, 6, 'CRYPTO', true),
    ('Filecoin', 'FIL', 'FIL', 'FIL', NULL, 18, 18, 'CRYPTO', true),
    ('VeChain', 'VET', 'VET', 'VET', NULL, 18, 18, 'CRYPTO', true),
    ('Internet Computer', 'ICP', 'ICP', 'ICP', NULL, 8, 8, 'CRYPTO', true),
    ('Hedera', 'HBAR', 'ℏ', 'ℏ', NULL, 8, 8, 'CRYPTO', true),
    ('Arbitrum', 'ARB', 'ARB', 'ARB', NULL, 18, 18, 'CRYPTO', true),
    ('Optimism', 'OP', 'OP', 'OP', NULL, 18, 18, 'CRYPTO', true),
    ('Near Protocol', 'NEAR', 'NEAR', 'NEAR', NULL, 24, 24, 'CRYPTO', true),
    ('Aptos', 'APT', 'APT', 'APT', NULL, 8, 8, 'CRYPTO', true),
    ('Sui', 'SUI', 'SUI', 'SUI', NULL, 9, 9, 'CRYPTO', true),
    ('Pepe', 'PEPE', 'PEPE', 'PEPE', NULL, 18, 18, 'CRYPTO', true),
    ('Render', 'RNDR', 'RNDR', 'RNDR', NULL, 18, 18, 'CRYPTO', true),
    ('Injective', 'INJ', 'INJ', 'INJ', NULL, 18, 18, 'CRYPTO', true),
    ('The Graph', 'GRT', 'GRT', 'GRT', NULL, 18, 18, 'CRYPTO', true),
    ('Maker', 'MKR', 'MKR', 'MKR', NULL, 18, 18, 'CRYPTO', true),
    ('Theta Network', 'THETA', 'THETA', 'THETA', NULL, 18, 18, 'CRYPTO', true),
    ('Fantom', 'FTM', 'FTM', 'FTM', NULL, 18, 18, 'CRYPTO', true),
    ('Lido DAO', 'LDO', 'LDO', 'LDO', NULL, 18, 18, 'CRYPTO', true),
    ('Toncoin', 'TON', 'TON', 'TON', NULL, 9, 9, 'CRYPTO', true)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    iso_num = EXCLUDED.iso_num,
    iso_digits = EXCLUDED.iso_digits,
    decimals = EXCLUDED.decimals,
    type = EXCLUDED.type;
