DATABASE_NAME: krachtix
SERVER_PORT: 80

IDENTITY_MS_BASE_URL: https://id.id.krachtix.com
JWT_ISSUER_URI: https://id.id.krachtix.com

AWS_ENDPOINT: https://s3.eu-west-1.amazonaws.com
AWS_S3_REGION: eu-west-1

ALLOWED_CORS_ORIGINS: "https://id.id.krachtix.com"

SPRING_CACHE_TYPE: hazelcast
HAZELCAST_CLIENT_ADDRESS: ledger-hazelcast:5701
HAZELCAST_CLUSTER_NAME: ledger-cluster

HIBERNATE_SEARCH_BACKEND_TYPE: elasticsearch
OPENSEARCH_HOSTS: ${OPENSEARCH_HOSTS:opensearch:9200}
OPENSEARCH_PROTOCOL: ${OPENSEARCH_PROTOCOL:https}
HIBERNATE_SEARCH_RUNTIME_ENABLED: true
HIBERNATE_SEARCH_INDEX_ON_STARTUP: false
