HIBERNATE_SEARCH_BACKEND_TYPE: elasticsearch
OPENSEARCH_HOSTS: ${OPENSEARCH_HOSTS:opensearch:9200}
OPENSEARCH_PROTOCOL: ${OPENSEARCH_PROTOCOL:http}
HIBERNATE_SEARCH_RUNTIME_ENABLED: true
HIBERNATE_SEARCH_INDEX_ON_STARTUP: true
