package com.krachtix.commons.webhook

enum class WebhookEventType {
    TRANSACTION_CREATED,
    TRANSACTION_COMPLETED,
    TRANSACTION_FAILED,
    TRANSACTION_REVERSED,
    DEPOSIT_COMPLETED,
    WITHDRAWAL_COMPLETED,
    HOLD_CREATED,
    HOLD_RELEASED,
    HOLD_CAPTURED,
    HOLD_EXPIRED,
    ACCOUNT_CREATED,
    ACCOUNT_BLOCKED,
    ACCOUNT_UNBLOCKED,
    CUSTOMER_CREATED,
    CUSTOMER_UPDATED,
    CAMPAIGN_CREATED,
    CAMPAIGN_REDEEMED,
    CAMPAIGN_EXPIRED,
    EXPORT_COMPLETED,
    EXPORT_FAILED,
    ADJUSTMENT_CREATED,
    ALL
}
